// <auto-generated />
namespace Tangent.CeviriDukkani.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class campaign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campaign));
        
        string IMigrationMetadata.Id
        {
            get { return "201608061907075_campaign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
