// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Tangent.CeviriDukkani.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userroletypeid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userroletypeid));
        
        string IMigrationMetadata.Id
        {
            get { return "201607032214546_userroletypeid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
