// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Tangent.CeviriDukkani.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201607040208109_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
