// <auto-generated />
namespace Tangent.CeviriDukkani.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class capacti_rate_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(capacti_rate_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201154559_capacti_rate_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
