// <auto-generated />
namespace Tangent.CeviriDukkani.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class company_price_offer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(company_price_offer));
        
        string IMigrationMetadata.Id
        {
            get { return "201608231246241_company_price_offer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
